import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#201f1f',
        'on-tertiary': '#68000a',
        'secondary-fixed': '#6bff8f',
        'on-background': '#e5e2e1',
        'on-error': '#690005',
        'secondary-container': '#00b954',
        'tertiary-container': '#ff7a73',
        'on-secondary-container': '#004119',
        'on-primary-fixed-variant': '#005236',
        'tertiary': '#ffb3ad',
        'error-container': '#93000a',
        'surface-bright': '#3a3939',
        'outline': '#86948a',
        'primary': '#4edea3',
        'surface-container-low': '#1c1b1b',
        'surface-variant': '#353534',
        'on-primary-fixed': '#002113',
        'outline-variant': '#3c4a42',
        'on-tertiary-fixed-variant': '#930013',
        'on-tertiary-container': '#79000e',
        'inverse-surface': '#e5e2e1',
        'surface-container-highest': '#353534',
        'primary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#410004',
        'surface-dim': '#131313',
        'on-primary': '#003824',
        'error': '#ffb4ab',
        'inverse-on-surface': '#313030',
        'surface-container-high': '#2a2a2a',
        'on-secondary': '#003915',
        'secondary': '#4ae176',
        'on-error-container': '#ffdad6',
        'surface-tint': '#4edea3',
        'surface-container-lowest': '#0e0e0e',
        'on-surface': '#e5e2e1',
        'surface': '#131313',
        'primary-container': '#10b981',
        'tertiary-fixed': '#ffdad7',
        'inverse-primary': '#006c49',
        'secondary-fixed-dim': '#4ae176',
        'on-secondary-fixed': '#002109',
        'on-secondary-fixed-variant': '#005321',
        'on-surface-variant': '#bbcabf',
        'tertiary-fixed-dim': '#ffb3ad',
        'on-primary-container': '#00422b',
        'background': '#131313',
        'primary-fixed': '#6ffbbe',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Inter'],
        label: ['Inter'],
        mono: ['JetBrains Mono'],
      },
    },
  },
  plugins: [],
} satisfies Config
